
all:
	gcc -Wall -o saibi_unpack saibi_unpack.c
	gcc -Wall -o unescape unescape.c
	gcc -Wall -o unpack unpack.c

#	g++ -Wall -o pack pack.c -lm
#	g++ -Wall -o hex hex.c -lm

clean:
	rm -f unescape unpack saibi_unpack
