/*!
 * \file comm_motor_conf.h
 * \brief
 *
 *
 * created by Kim Youngmin (ymkim@huvitz.com)
 * creation date : 금  7월 27 09:44:59 KST 2007
 *
*/
#ifndef _COMM_MOTOR_CONF_H_
#define _COMM_MOTOR_CONF_H_

#define CALIBRATION_FLOAT_MULTIPLY_VALUE  100

// motor conf data index
// same as old motor_calibration.h

#define I_POS_GROOVE_X			0
#define I_POS_GROOVE_30MM			1
#define I_GROOVE_START_ANGLE			2
#define I_POS_GROOVE_ANGLE			3
#define I_POS_SFB_X_REAR			4
#define I_POS_SFB_X_FRONT			5
#define I_POS_SFB_30MM			6
#define I_SFB_START_ANGLE			7
#define I_POS_SFB_ANGLE			8
#define I_POS_Y_ZERO			9
#define I_POS_Y_ZERO_ANGLE			10

#define I_INIT_VALUE_OF_ROTATION			11
#define I_FEELER_REAR_OFFSET			12
#define I_FEELER_FRONT_OFFSET			13
#define I_FEELER_START_ANGLE_17MM_REAR			14
#define I_FEELER_START_ANGLE_17MM_FRONT			15
#define I_POS_FEELER_20MM_REAR			16
#define I_POS_FEELER_20MM_FRONT			17
#define I_L_ROTATION_LIMIT_ROUGH			18
#define I_L_ROTATION_LIMIT_POLISH_MIN			19
#define I_L_ROTATION_LIMIT_POLISH_MAX			20

#define I_L_ROTATION_LIMIT_FINISH_MIN			21
#define I_L_ROTATION_LIMIT_FINISH_MAX			22
#define I_L_ROUGH_Y_SPEED_SAFE			23
#define I_L_ROUGH_Y_SPEED_NORMAL			24
#define I_L_ROTATION_SPEED_ROUGH_PLASTIC			25
#define I_L_ROTATION_SPEED_ROUGH_PC			26
#define I_L_ROTATION_SPEED_ROUGH_GLASS			27
#define I_L_ROTATION_SPEED_ROUGH_HI			28
#define I_L_ROTATION_SPEED_ROUGH_TV			29
#define I_L_ROTATION_SPEED_FINISH_PLASTIC			30

#define I_L_ROTATION_SPEED_FINISH_PC			31
#define I_L_ROTATION_SPEED_FINISH_GLASS			32
#define I_L_ROTATION_SPEED_FINISH_HI			33
#define I_L_ROTATION_SPEED_FINISH_TV			34
#define I_L_ROTATION_SPEED_POLISH_PLASTIC			35
#define I_L_ROTATION_SPEED_POLISH_PC			36
#define I_L_ROTATION_SPEED_POLISH_HI			37
#define I_L_ROTATION_SPEED_POLISH_TV			38
#define I_L_ROTATION_SPEED_FEEL			39
#define I_L_ROTATION_SPEED_SB			40

#define I_L_ROTATION_SPEED_GROOVE			41
#define I_E_SAMPLING_SIZE			42
#define I_F_WHEEL_SETTING_PLASTIC_ROUGH			43
#define I_F_WHEEL_SETTING_GLASS_ROUGH			44
#define I_F_WHEEL_SETTING_FINISH_BEVEL			45
#define I_F_WHEEL_SETTING_FINISH_RIMLESS			46
#define I_F_WHEEL_SETTING_POLISH_BEVEL			47
#define I_F_WHEEL_SETTING_POLISH_RIMLESS			48
#define I_F_SIZE_ADJUSTMENT_FINISH_PLASTIC_BEVEL			49
#define I_F_SIZE_ADJUSTMENT_FINISH_PLASTIC_RIMLESS			50

#define I_F_SIZE_ADJUSTMENT_FINISH_PC_BEVEL			51
#define I_F_SIZE_ADJUSTMENT_FINISH_PC_RIMLESS			52
#define I_F_SIZE_ADJUSTMENT_FINISH_GLASS_BEVEL			53
#define I_F_SIZE_ADJUSTMENT_FINISH_GLASS_RIMLESS			54
#define I_F_SIZE_ADJUSTMENT_FINISH_HI_BEVEL			55
#define I_F_SIZE_ADJUSTMENT_FINISH_HI_RIMLESS			56
#define I_F_SIZE_ADJUSTMENT_FINISH_TV_BEVEL			57
#define I_F_SIZE_ADJUSTMENT_FINISH_TV_RIMLESS			58
#define I_F_SIZE_ADJUSTMENT_POLISH_PLASTIC_BEVEL			59
#define I_F_SIZE_ADJUSTMENT_POLISH_PLASTIC_RIMLESS			60

#define I_F_SIZE_ADJUSTMENT_POLISH_PC_BEVEL			61
#define I_F_SIZE_ADJUSTMENT_POLISH_PC_RIMLESS			62
#define I_F_SIZE_ADJUSTMENT_POLISH_HI_BEVEL			63
#define I_F_SIZE_ADJUSTMENT_POLISH_HI_RIMLESS			64
#define I_F_SIZE_ADJUSTMENT_POLISH_TV_BEVEL			65
#define I_F_SIZE_ADJUSTMENT_POLISH_TV_RIMLESS			66
#define I_F_SIZE_ADJUSTMENT_MASTER_SIZE			67
#define I_F_MARGIN_ADJUSTMENT_ROUGH_PLASTIC_BEVEL			68
#define I_F_MARGIN_ADJUSTMENT_ROUGH_PLASTIC_RIMLESS			69
#define I_F_MARGIN_ADJUSTMENT_ROUGH_PC_BEVEL			70

#define I_F_MARGIN_ADJUSTMENT_ROUGH_PC_RIMLESS			71
#define I_F_MARGIN_ADJUSTMENT_ROUGH_GLASS_BEVEL			72
#define I_F_MARGIN_ADJUSTMENT_ROUGH_GLASS_RIMLESS			73
#define I_F_MARGIN_ADJUSTMENT_ROUGH_HI_BEVEL			74
#define I_F_MARGIN_ADJUSTMENT_ROUGH_HI_RIMLESS			75
#define I_F_MARGIN_ADJUSTMENT_ROUGH_TV_BEVEL			76
#define I_F_MARGIN_ADJUSTMENT_ROUGH_TV_RIMLESS			77
#define I_F_MARGIN_ADJUSTMENT_POLISH_PLASTIC_BEVEL			78
#define I_F_MARGIN_ADJUSTMENT_POLISH_PLASTIC_RIMLESS			79
#define I_F_MARGIN_ADJUSTMENT_POLISH_PC_BEVEL			80

#define I_F_MARGIN_ADJUSTMENT_POLISH_PC_RIMLESS			81
#define I_F_MARGIN_ADJUSTMENT_POLISH_HI_BEVEL			82
#define I_F_MARGIN_ADJUSTMENT_POLISH_HI_RIMLESS			83
#define I_F_MARGIN_ADJUSTMENT_POLISH_TV_BEVEL			84
#define I_F_MARGIN_ADJUSTMENT_POLISH_TV_RIMLESS			85
#define I_F_MARGIN_ADJUSTMENT_SUB_FINISH_PC_BEVEL			86
#define I_F_MARGIN_ADJUSTMENT_SUB_FINISH_PC_RIMLESS			87
#define I_F_MARGIN_ADJUSTMENT_SUB_FINISH_TV_BEVEL			88
#define I_F_MARGIN_ADJUSTMENT_SUB_FINISH_TV_RIMLESS			89
#define I_F_MARGIN_ADJUSTMENT_SUB_POLISH_PC_BEVEL			90

#define I_F_MARGIN_ADJUSTMENT_SUB_POLISH_PC_RIMLESS			91
#define I_F_MARGIN_ADJUSTMENT_SUB_POLISH_TV_BEVEL			92
#define I_F_MARGIN_ADJUSTMENT_SUB_POLISH_TV_RIMLESS			93
#define I_F_AXIS_ADJUSTMENT_NORMAL_PLASTIC			94
#define I_F_AXIS_ADJUSTMENT_NORMAL_PC			95
#define I_F_AXIS_ADJUSTMENT_NORMAL_GLASS			96
#define I_F_AXIS_ADJUSTMENT_NORMAL_HI			97
#define I_F_AXIS_ADJUSTMENT_NORMAL_TV			98
#define I_F_AXIS_ADJUSTMENT_GROOVE_PLASTIC			99
#define I_F_AXIS_ADJUSTMENT_GROOVE_PC			100

#define I_F_AXIS_ADJUSTMENT_GROOVE_HI			101
#define I_F_AXIS_ADJUSTMENT_GROOVE_TV			102
#define I_F_AXIS_ADJUSTMENT_SB_FRONT_PLASTIC			103
#define I_F_AXIS_ADJUSTMENT_SB_FRONT_PC			104
#define I_F_AXIS_ADJUSTMENT_SB_FRONT_GLASS			105
#define I_F_AXIS_ADJUSTMENT_SB_FRONT_HI			106
#define I_F_AXIS_ADJUSTMENT_SB_FRONT_TV			107
#define I_F_AXIS_ADJUSTMENT_SB_REAR_PLASTIC			108
#define I_F_AXIS_ADJUSTMENT_SB_REAR_PC			109
#define I_F_AXIS_ADJUSTMENT_SB_REAR_GLASS			110

#define I_F_AXIS_ADJUSTMENT_SB_REAR_HI			111
#define I_F_AXIS_ADJUSTMENT_SB_REAR_TV			112
#define I_F_AXIS_ADJUSTMENT_POLISH_PLASTIC			113
#define I_F_AXIS_ADJUSTMENT_POLISH_PC			114
#define I_F_AXIS_ADJUSTMENT_POLISH_HI			115
#define I_F_AXIS_ADJUSTMENT_POLISH_TV			116
#define I_F_POSITION_ADJUSTMENT_BEVEL			117
#define I_F_POSITION_ADJUSTMENT_POLISHED_BEVEL			118
#define I_F_GROOVE_ADJUSTMENT_DEPTH			119
#define I_F_GROOVE_ADJUSTMENT_WIDTH			120

#define I_F_GROOVE_ADJUSTMENT_POSITION			121
#define I_F_SB_ADJUSTMENT_BEVELED_FRONT_PLASTIC			122
#define I_F_SB_ADJUSTMENT_BEVELED_FRONT_PC			123
#define I_F_SB_ADJUSTMENT_BEVELED_FRONT_GLASS			124
#define I_F_SB_ADJUSTMENT_BEVELED_FRONT_HI			125
#define I_F_SB_ADJUSTMENT_BEVELED_FRONT_TV			126
#define I_F_SB_ADJUSTMENT_BEVELED_REAR_PLASTIC			127
#define I_F_SB_ADJUSTMENT_BEVELED_REAR_PC			128
#define I_F_SB_ADJUSTMENT_BEVELED_REAR_GLASS			129
#define I_F_SB_ADJUSTMENT_BEVELED_REAR_HI			130

#define I_F_SB_ADJUSTMENT_BEVELED_REAR_TV			131
#define I_F_SB_ADJUSTMENT_RIMLESS_FRONT_PLASTIC			132
#define I_F_SB_ADJUSTMENT_RIMLESS_FRONT_PC			133
#define I_F_SB_ADJUSTMENT_RIMLESS_FRONT_GLASS			134
#define I_F_SB_ADJUSTMENT_RIMLESS_FRONT_HI			135
#define I_F_SB_ADJUSTMENT_RIMLESS_FRONT_TV			136
#define I_F_SB_ADJUSTMENT_RIMLESS_REAR_PLASTIC			137
#define I_F_SB_ADJUSTMENT_RIMLESS_REAR_PC			138
#define I_F_SB_ADJUSTMENT_RIMLESS_REAR_GLASS			139
#define I_F_SB_ADJUSTMENT_RIMLESS_REAR_HI			140

#define I_F_SB_ADJUSTMENT_RIMLESS_REAR_TV			141
#define I_L_CLAMP_PRESSURE_PLASTIC			142
#define I_L_CLAMP_PRESSURE_PC			143
#define I_L_CLAMP_PRESSURE_GLASS			144
#define I_L_CLAMP_PRESSURE_HI			145
#define I_L_CLAMP_PRESSURE_TV			146
#define I_F_POLISH_WHEEL_SIZE			147

enum comm_motor_conf_idx_continue {
	FS_CLAMP_OPEN_TIMEOUT = 148,
	FS_CLAMP_MOTOR_VOLTAGE_WEAK,
	FS_CLAMP_MOTOR_VOLTAGE_STRONG,

	FS_CLAMP_CLOSE_THRESHOLD, // 151
	FS_CLAMP_CLOSE_STRONG_STANDARD_FORCE,
	FS_CLAMP_STRONG_TIMEOUT,
	FS_FEELER_STROKE,
	FS_GROOVE_STROKE,
	FS_GROOVE_RETURN_STROKE,
	FS_POS_FEELER_CENTER,
	FS_POS_FEELER_REAR,
	FS_POS_FEELER_FRONT,
	FS_POS_FEELER_20MM_FOR_CALIBRATION,

	FS_Y_SCALE_PITCH, // 161
	FS_X_SCALE_DIA,
	FS_SBG_MOTOR_CURRENT_LIMIT,
	FS_GROOVE_CAL_START_X_POS,
	FS_SB_CAL_START_X_POS,
	FS_FEELER_UPDN_SPEED_HI,
	FS_SBG_UPDN_SPEED_HI,
	FS_R_UPDN_SPEED_HI,
	FS_X_UPDN_SPEED_HI,
	FS_Y_UPDN_SPEED_HI,

	MCI_ROUGHING_PL_DIR, // 171
	MCI_EDGER_CONTROL_DATA, 
	MCI_GROOVING_MARGIN,
	MCI_SFB_MARGIN,
	MCI_MAX_RIMLESS_THICKNESS,
	MCI_INV_FREQ_HI,
	MCI_INV_FREQ_LO,
	MCI_GROOVE_DIAGONAL_COMPEN_UPPER_RIGHT,
	MCI_GROOVE_DIAGONAL_COMPEN_UPPER_LEFT,
	MCI_SB_COMPEN_FRONT_BEVEL,

	MCI_SB_COMPEN_REAR_BEVEL, // 181
	MCI_SB_COMPEN_FRONT_RIMLESS,
	MCI_SB_COMPEN_REAR_RIMLESS,
	MCI_BEVEL_HEIGHT, 
	MCI_EDGER_CONTROL_DATA2, // 20071015 추가 
	MCI_EDGING_NEXT_STEP_Y, // 20071022
	MCI_Y_UP_DELAY, // 20071022
	MCI_L_ROTATION_SPEED_GROOVE_PC_TRI,  // 20071023
	MCI_POL_X_FIX_WHEEL_OFFSET, // 20071024 polishing x fix wheel offset
	MCI_R_LOW_SPEED, // 20071025

	MCI_ROTATION_LIMIT_GROOVING, // 20071116 grooving rotation limit // 191
	MCI_ROTATION_LIMIT_GROOVING_TRI, // 20071116 grooving rotation limit
	MCI_ROUGHING_CONTACT_SENSITIVITY, // 20071203 러핑 컨택트 감도 설정 
	MCI_SBG_OC_LIMIT, // 20080108 새로운 sbg over current 검사 변수
	MCI_SBG_OC_RANGE, // 20080108
	MCI_SBG_OC_COUNT, // 20080108
	MCI_SBG_ABNORMAL_RANGE, // 20080108
	MCI_SBG_ABNORMAL_COUNT, // 20080108
	MCI_FRAME_CHANGE_OFFSET, // 20090114

	MAX_MOTOR_CONF_IDX
};

extern char *comm_motor_conf_str[MAX_MOTOR_CONF_IDX];

int send_cpe_motor_conf_data_ex(int uart, int *conf_data, int from, int to);
int parse_cpe_motor_conf_data_ex(char *buf, int *conf_data, int from, int to);
int recv_cpe_motor_conf_data_ex(int uart, int *conf_data, int from, int to, int time_out);
int send_cpe_motor_calibration_data(int uart, int *cal_data);
int recv_cpe_motor_calibration_data(int uart, int *cal_data, int time_out);
int send_cpe_motor_conf_data(int uart, int *conf_data);
int recv_cpe_motor_conf_data(int uart, int *conf_data, int time_out);
int get_cpe_motor_conf_data(char *buf, int *conf_data);

#endif
/********** end of file **********/

